#!/usr/bin/env bash

# set -e

if [ -z "$1" ]; then
  echo "ERROR: an ID must be supplied"
  exit 1
fi

./pantiltcam.py &
SERVER_PID=$!

chromium-browser --headless --enable-logging=stderr --remote-debugging-pipe --use-fake-ui-for-media-stream https://lucaong.github.io/pantiltcam/camera.html#$1

trap kill -9 $SERVER_PID EXIT SIGINT SIGTERM
