#!/usr/bin/env bash

# set -e

if [ -z "$1" ]; then
  echo "ERROR: an ID must be supplied"
  exit 1
fi

./pantiltcam.py &
SERVER_PID=$!

trap shutdown_server EXIT SIGHUP SIGINT SIGQUIT SIGTERM

chromium-browser --headless --enable-logging=stderr --remote-debugging-pipe --use-fake-ui-for-media-stream https://lucaong.github.io/pantiltcam/camera.html#$1

shutdown_server()
{
  echo "Shutting down server (PID $SERVER_PID)"
  kill $SERVER_PID
  exit
}
